name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    - name: Run phpstan
      run: composer run-script stan

    - name: Run tests
      run: composer run-script test

    - name: clover summary
      uses: GregorLohaus/CloverCodeCoverageSummary@025f2cc9f78ee8cd80f66f15ce31e40a729062e9
      with:
        filename: clover.xml

    - name: 'code coverage to step summary'
      run: | 
          cat code-coverage-summary.md >> $GITHUB_STEP_SUMMARY
      run:
          cat code-coverage-details.md >> $GITHUB_STEP_SUMMARY
